root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  bin = "tmp/main.exe"

  include_dir = ["internal", "cmd", "pkg"]
  include_ext = ["go"]

  exclude_dir = ["tmp", "vendor", "testdata", "assets"]

  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = "0.2s"

[color]
  build = "yellow"
  runner = "green"
  watcher = "cyan"

[log]
  time = true
